<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        @page { margin: 18mm 12mm; }
        body { font-family: "DejaVu Sans", sans-serif; font-size: {{ $fontSize }}; color: #111; }
        h1 { font-size: 14pt; margin: 0 0 4px; }
        .meta { color: #555; margin-bottom: 10px; }
        .meta div { margin: 1px 0; }
        table { width: 100%; border-collapse: collapse; table-layout: fixed; }
        td, th { word-wrap: break-word; }
        th { background: #f1f1f1; text-align: left; font-weight: bold; }
        th, td { border: 1px solid #ccc; padding: 3px 5px; vertical-align: top; }
        td.num, th.num { text-align: right; }
        td.date { white-space: nowrap; }
        tfoot td { font-weight: bold; background: #f7f7f7; }
        .neg { color: #b91c1c; }
        .empty { text-align: center; color: #777; padding: 16px; }
        .footer { position: fixed; bottom: -10mm; left: 0; right: 0; font-size: 7pt; color: #777; }
    </style>
</head>
<body>
    <h1>{{ $title }}</h1>
    <div class="meta">
        @foreach ($meta as $label => $value)
            <div><strong>{{ $label }}:</strong> {{ $value }}</div>
        @endforeach
    </div>

    <table>
        <thead>
            <tr>
                @foreach ($columns as $c)
                    <th class="{{ in_array($c['type'], ['money', 'int']) ? 'num' : '' }}">{{ $c['label'] }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @forelse ($rows as $row)
                <tr>
                    @foreach ($row as $i => $value)
                        @php($numeric = in_array($columns[$i]['type'], ['money', 'int']))
                        <td class="{{ $numeric ? 'num' : '' }} {{ $columns[$i]['type'] === 'date' ? 'date' : '' }} {{ $numeric && str_starts_with($value, '-') ? 'neg' : '' }}">{{ $value }}</td>
                    @endforeach
                </tr>
            @empty
                <tr><td colspan="{{ count($columns) }}" class="empty">No records match these filters.</td></tr>
            @endforelse
        </tbody>
        @if ($totals && count($rows) > 0)
            <tfoot>
                <tr>
                    @foreach ($totals as $i => $value)
                        <td class="{{ in_array($columns[$i]['type'], ['money', 'int']) ? 'num' : '' }}">{{ $value }}</td>
                    @endforeach
                </tr>
            </tfoot>
        @endif
    </table>

    @foreach ($summaries as $summary)
        <h2 style="font-size: 10.5pt; margin: 16px 0 6px;">{{ $summary['title'] }}</h2>
        <table style="width: auto; min-width: 50%;">
            <thead>
                <tr>
                    @foreach ($summary['columns'] as $c)
                        <th class="{{ in_array($c['type'], ['money', 'int']) ? 'num' : '' }}">{{ $c['label'] }}</th>
                    @endforeach
                </tr>
            </thead>
            <tbody>
                @foreach ($summary['rows'] as $row)
                    <tr>
                        @foreach ($row as $i => $value)
                            <td class="{{ in_array($summary['columns'][$i]['type'], ['money', 'int']) ? 'num' : '' }}">{{ $value }}</td>
                        @endforeach
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endforeach

    <div class="footer">Generated by MM Business Platform. Figures are calculated by the system from active (non-reversed) records.</div>
</body>
</html>
